AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket S3 de entrada

Parameters:
  BucketName:
    Type: String
    Description: Bucket S3 de entrada

Resources:
  InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  InputBucketName:
    Description: Nombre del bucket S3 creado
    Value: !Ref InputBucket